language: python
cache: pip
python:
- 3.6
services:
- mongodb
before_script:
- sleep 15
before_install:
- openssl aes-256-cbc -K $encrypted_a0a687274364_key -iv $encrypted_a0a687274364_iv
  -in travis-secrets.tar.enc -out travis-secrets.tar -d
- tar xvf travis-secrets.tar
install:
- pip install -r requirements.txt
script:
- python test.py
before_deploy:
- eval "$(ssh-agent -s)"
- chmod 400 gsbot-ec2.pem
- ssh-add gsbot-ec2.pem
- echo $PUBLIC_SSH_KEY >> $HOME/.ssh/known_hosts
deploy:
  provider: script
  script: ssh $EC2_SSH -i gsbot-ec2.pem screen -d -m 'sh ~/scripts/gsbot-deploy.sh'
  on:
    branch: prod
