language: python
cache: pip
python:
- 3.6
services:
- mongodb
before_script:
  - sleep 15
before_install:
- openssl aes-256-cbc -K $encrypted_a0a687274364_key -iv $encrypted_a0a687274364_iv -in config.ini.enc -out config.ini -d
install:
- pip install -r requirements.txt
script:
- python test.py

